language: node_js

node_js: stable

stages:
  # - name: test
    if: NOT type = push
  - name: build
    if: branch IN (develop, master)
  - name: deploy
    if: branch IN (develop, master) AND (NOT (type = pull_request))

before_script:
  npm update -g npm

cache:
  directories:
  - node_modules

jobs:
  include:
    # - stage: test
      # script: "npm run test"
    - stage: build
      script: chmod +x ./scripts/build.sh && bash ./scripts/build.sh
    - stage: deploy
      skip_cleanup: true
      script: chmod +x ./scripts/deploy.sh && bash ./scripts/deploy.sh
