language: node_js

node_js: stable

stages:
  # - name: test
  #   if: NOT (branch = master) AND NOT (branch = develop)
  - name: build
    if: branch IN (develop, master)
  - name: deploy
    if: branch IN (develop, master)

before_script:
  npm update -g npm

cache:
  directories:
  - node_modules

# Travis CI process.
# Cleanup is skipped so install / build output will remain in tact during deploy
jobs:
  include:
    # - stage: test
      # script: "npm run test"
    - stage: build
      script: chmod +x ./scripts/build.sh && bash ./scripts/build.sh
    - stage: deploy
      skip_cleanup: true
      script:
        curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
        unzip awscli-bundle.zip
        ./awscli-bundle/install -b ~/bin/aws
        export PATH=~/bin:$PATH
        chmod +x ./scripts/deploy.sh && bash ./scripts/deploy.sh

# pull down aws cli
before_deploy:
  - 